name: tp_donut_chart
description: A customizable and responsive donut chart widget for Flutter, supporting up to 10 entries with rounded gaps, hover effect, and central value/label styling.
version: 0.0.4

repository: https://github.com/pradoui/tp_donut_chart.git
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
