name: tp_donut_chart
description: Um widget de gráfico donut personalizável para Flutter.
version: 0.0.3

repository: https://github.com/pradoui/tp_donut_chart.git
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
